### ISSUE TITLE
Fatal error when use ObjectManager static methods

### ISSUE THREAD

**Issue by OleksiiStepanov** [magento/magento-coding-standard#323]
### Preconditions

1. Use v14 
 

### Steps to reproduce

1. create some class with function that call `ObjectManager::setInstance($defaultObjectManager);`
2.

### Expected result

1. No errors

### Actual result

1. Got error: 
`
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Magento2\Sniffs\PHP\AutogeneratedClassNotInConstructorSniff::validateRequestedClass() must be of the type int, bool given, called in /home/runner/work/ecommerce-backend/ecommerce-backend/magento-coding-standard/Magento2/Sniffs/PHP/AutogeneratedClassNotInConstructorSniff.php on line 52 and defined in /home/runner/work/ecommerce-backend/ecommerce-backend/magento-coding-standard/Magento2/Sniffs/PHP/AutogeneratedClassNotInConstructorSniff.php:75
Stack trace:
#0 /home/runner/work/ecommerce-backend/ecommerce-backend/magento-coding-standard/Magento2/Sniffs/PHP/AutogeneratedClassNotInConstructorSniff.php(52): Magento2\Sniffs\PHP\AutogeneratedClassNotInConstructorSniff->validateRequestedClass()
#1 /home/runner/work/ecommerce-backend/ecommerce-backend/magento-coding-standard/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): Magento2\Sniffs\PHP\AutogeneratedClassNotInConstructorSniff->process()
#2 /home/runner/work/ecommerce-backend/ecommerce-backend/magento-coding-standa in /home/runner/work/ecommerce-backend/ecommerce-backend/magento-coding-standard/Magento2/Sniffs/PHP/AutogeneratedClassNotInConstructorSniff.php on line 75
Error: Error: Command failed: magento-coding-standard/vendor/bin/phpcs --report=checkstyle --standard=Magento2 app/code/DBI/MessageQueue/Consumer/ConsumerFactory.php app/code/DBI/MessageQueue/Consumer/Isolator.php
`

**Comment by itaymesh** [comment]
@OleksiiStepanov hi, 
we are getting the same error. 
Did you find out how to fix or work around it?

**Comment by fredden** [comment]
This was fixed in https://github.com/magento/magento-coding-standard/pull/336.

@itaymesh please upgrade to version 16 or better.

**Comment by itaymesh** [comment]
@fredden thanks for your quick reply.
I am already using the latest version. 
As a temporary workaround, I added `// phpcs:ignoreFile`

**Comment by fredden** [comment]
@itaymesh Please can you open a new issue with a description of the problem, and ideally a sample file showing the behaviour you're seeing.
